version: '3.8'

services:
  vaultguard-executor:
    image: vaultguard/agent-executor:latest

  vaultguard-agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    volumes:
      - ./agent/db/:/app/db
      - ./agent/code:/app/code
      - ./agent/src:/app/src
      - ./agent/scripts:/app/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - intelligence_cache:/app/cache
    environment:
      - PYTHONPATH=/app
      - SQLITE_PATH=/app/db/vaultguard.db
      - RAG_URL=http://rag-api:8080
      - COMMUNITY_DB_API_URL=http://community-db-api:8082
      - CACHE_INTELLIGENCE=true
    command: sleep infinity
    networks:
      - vaultguard-network
    env_file:
      - ./examples/.env.quickstart

  background-learning-engine:
    build:
      context: ./agent
      dockerfile: docker/Dockerfile.learning
    environment:
      - REDIS_URL=redis://rag-redis:6379
      - COMMUNITY_DB_API_URL=http://community-db-api:8082
      - RAG_URL=http://rag-api:8080
      - JUPITER_API_URL=https://quote-api.jup.ag/v6
      - DEFI_LLAMA_API_URL=https://api.llama.fi
      - PYTHONPATH=/app
    depends_on:
      - rag-redis
      - community-db-api
      - rag-api
    volumes:
      - ./agent/src:/app/src
      - intelligence_cache:/app/cache
    networks:
      - vaultguard-network
    env_file:
      - ./examples/.env.quickstart

  external-data-connector:
    build:
      context: ./agent
      dockerfile: docker/Dockerfile.external
    environment:
      - JUPITER_API_URL=https://quote-api.jup.ag/v6
      - DEFI_LLAMA_API_URL=https://api.llama.fi
      - COMMUNITY_DB_API_URL=http://community-db-api:8082
      - REDIS_URL=redis://rag-redis:6379
      - PYTHONPATH=/app
    depends_on:
      - rag-redis
      - community-db-api
    volumes:
      - intelligence_cache:/app/cache
    networks:
      - vaultguard-network
    env_file:
      - ./examples/.env.quickstart

  community-db-api:
    build:
      context: ./community-db-api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://community:community@community-db:5432/community_db
      - REDIS_URL=redis://community-redis:6379
      - PORT=8082
      - NODE_ENV=development
    depends_on:
      - community-db
      - community-redis
    ports:
      - "8082:8082"
    networks:
      - vaultguard-network
    env_file:
      - ./examples/.env.quickstart

  community-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=community_db
      - POSTGRES_USER=community
      - POSTGRES_PASSWORD=community
    volumes:
      - community_db_data:/var/lib/postgresql/data
    networks:
      - vaultguard-network

  community-redis:
    image: redis:7-alpine
    volumes:
      - community_redis_data:/data
    networks:
      - vaultguard-network

  rag-redis:
    image: redis:7-alpine
    volumes:
      - rag_redis_data:/data
    networks:
      - vaultguard-network

  rag-api:
    build:
      context: ./rag-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - vaultguard-network
    environment:
      - PORT=8080
      - NODE_ENV=development
      - BACKGROUND_PROCESSING=true
      - REDIS_URL=redis://rag-redis:6379
    depends_on:
      - rag-redis
    env_file:
      - ./examples/.env.quickstart
    
volumes:
  community_db_data:
  community_redis_data:
  rag_redis_data:
  intelligence_cache:

networks:
  vaultguard-network:
    driver: bridge